[versions]
agp = "8.13.2"
appcompat = "1.7.1"
coreKtx = "1.17.0"
desugar_jdk_libs = "2.1.5"
kotlin = "2.1.21"
kotlinxCoroutinesAndroid = "1.10.2"
# Remarks:
# - We're explicitly using an old version (1.0.32) because versions 1.0.33 up to (at least) 1.0.35
#   causes this specific issue on Android 7 (https://github.com/wonday/react-native-pdf/issues/979)
#   which prevents PDFs to load. If a new version fixes it then please update to that version.
pdfiumandroid = "1.0.32"

[libraries]
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "coreKtx" }
desugar_jdk_libs = { module = "com.android.tools:desugar_jdk_libs", version.ref = "desugar_jdk_libs" }
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlin" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinxCoroutinesAndroid" }
pdfiumandroid = { module = "io.legere:pdfiumandroid", version.ref = "pdfiumandroid" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
androidLibrary = { id = "com.android.library", version.ref = "agp" }
kotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
